/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package linkcrawler;


import java.util.regex.Matcher;

/**
 *
 * @author Har
 */
public class CrawlerJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CrawlerJFrame
     */
    JavaSpider js;
    Thread match;
    public CrawlerJFrame() {
        initComponents();
        js = new JavaSpider();
        jTextArea1.setLineWrap(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("新闻网址:");

        jButton1.setText("获取");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("介绍:\n针对网易娱乐新闻的正则匹配,输入新闻网址,匹配出新闻相关信息,以及在该网页中出现的其他新闻链接\n\n使用方法:\n选中链接后将自动填充至\"新闻网址\",点击获取\n\n");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setText("标题:");

        jLabel3.setText("时间:");

        jLabel4.setText("正文");

        jLabel5.setText("链接");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("示例网址:\nhttp://ent.sina.com.cn/m/c/2016-11-26/doc-ifxyawmp0251803.shtml\nhttp://ent.sina.com.cn/m/c/2016-11-26/doc-ifxyawmp0262569.shtml\nhttp://ent.sina.com.cn/zl/discuss/2016-11-25/doc-ifxyawmp0090354.shtml\nhttp://ent.sina.com.cn/zl/bagua/2016-11-25/doc-ifxyawmp0091774.shtml");
        jTextArea2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jTextArea2MouseDragged(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea2);

        jButton2.setText("清空");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3)
                            .addComponent(jTextField2))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String url = jTextField1.getText();  
	String urlHtml = js.UrlCrawler(url);
        if(urlHtml.equals("error")){
            jTextArea1.setText("请求失败,网址可能有误");
        }
        else{
            jTextArea1.setText("");
            jTextArea2.setText("");
        }
        jTextField2.setText("");
        jTextField3.setText("");
        
        Matcher urlMatcher = js.regexString(urlHtml, "href=\"(http[s]?://ent.{0,30}\\d{4}-\\d{2}-\\d{2}.{0,30}shtml)\"");
        Matcher titleMatcher = js.regexString(urlHtml, "<.*?id=\".*?itle\".*?>(.*?)</h1>");
        Matcher timeMatcher = js.regexString(urlHtml, "<span.*?id=\"navtimeSource\">(.*?)<span>");
        Matcher timeMatcher2 = js.regexString(urlHtml, "<span class=\"titer\">(.*?)</span>");
        Matcher timeMatcher3 = js.regexString(urlHtml, "<span id=\"pub_date\">(.*?)</span>");
        Matcher contentLineMatcher = js.regexString(urlHtml, "<p.*?>(.*?)</p>");
	String line;
        if (titleMatcher.find()){
            jTextField2.setText(titleMatcher.group(1));
        }
        if (timeMatcher.find()){
            jTextField3.setText(timeMatcher.group(1));
        }
        else if (timeMatcher2.find()){
            jTextField3.setText(timeMatcher2.group(1));
        }
        else if (timeMatcher3.find()){
            jTextField3.setText(timeMatcher3.group(1));
        }
        while (contentLineMatcher.find()){
            line = contentLineMatcher.group(1).replaceAll("<.*?>", "").replaceAll("&nbsp", "")+'\n';
            if(line.contains("新浪简介")){
                break;
            }
            jTextArea1.append(line);   
        }
        while (urlMatcher.find()){
            jTextArea2.append(urlMatcher.group(1)+'\n');
        }
        jTextArea1.setCaretPosition(0);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextArea1.setText("");
        jTextArea2.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextArea2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea2MouseDragged
        // TODO add your handling code here:
        jTextField1.setText(jTextArea2.getSelectedText());
    }//GEN-LAST:event_jTextArea2MouseDragged

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
